--
--
/******************************************************************************
 * Description: Start partioning of table.
 * Author: Ypahariya
 *
 ******************************************************************************/

SET SERVEROUTPUT ON
SET TIMING ON
SET LINESIZE 180
 
DECLARE

  --IV_TABLE_NAME VARCHAR2(200) := 'RID_AUDIT_LOG';
  --IV_TABLE_NAME_SHORT VARCHAR2(20) := 'RID_AUDIT_LOG';
  --IV_PART_COLUMN      VARCHAR2(30) := 'LOG_DATE';

  --IV_TABLE_NAME VARCHAR2(200) := 'EXPECTED_MOVEMENT';
  --IV_TABLE_NAME_SHORT VARCHAR2(20) := 'EXPMVT';
  --IV_PART_COLUMN      VARCHAR2(30) := 'EXPECTED_DATE';
  IV_TABLE_NAME VARCHAR2(200) := 'TRANSACTION_DETAIL_LOG';
  IV_TABLE_NAME_SHORT VARCHAR2(20) := 'TXN_DETAIL_LOG';
  IV_PART_COLUMN      VARCHAR2(30) := 'TRANSACTION_DATE';
  IN_NUM_OF_PARTITIONS NUMBER := 30;
BEGIN

  PKG_PARTITION_MIGRATION.PR_PARTITION_TABLE(
    IV_TABLE_NAME 		=> IV_TABLE_NAME,
	IV_TABLE_NAME_SHORT => IV_TABLE_NAME_SHORT,
    IN_NUM_OF_PARTITIONS=> IN_NUM_OF_PARTITIONS,
	IV_PART_COLUMN		=>  IV_PART_COLUMN,
	IV_PART_SCHEME		=> 'MONTHLY'
  );
END;
/
